DROP DATABASE IF EXISTS DAEITESMCCV;
CREATE DATABASE DAEITESMCCV;
USE DAEITESMCCV;

DROP TABLE IF EXISTS Alumnos;
CREATE TABLE Alumnos(
	Matricula	TEXT(9)		NOT NULL,
	Nombre		TEXT(50)	NOT NULL,
	Apellido	TEXT(50)	NOT NULL,
	Password	TEXT(50)	NOT NULL
);

DROP TABLE IF EXISTS Administradores;
CREATE TABLE Administradores(
	Nomina		TEXT(9)		NOT NULL,
	Password	TEXT(50)	NOT NULL
);

DROP TABLE IF EXISTS Actividades;
CREATE TABLE Actividades(
	Id				INT			NOT NULL,
	Alumno			INT			NOT NULL,
	Tipo			INT			NOT NULL,
	Nombre			TEXT(50)	NOT NULL,
	Descripcion		TEXT(50)	NOT NULL,
	Rol				INT			NOT NULL,
	Periodo			INT			NOT NULL,
	AreaImpacto		INT			NOT NULL,
	Aprendizajes	TEXT(50)	NOT NULL,
	Competencias	TEXT(50)	NOT NULL,
	PRIMARY KEY (Id)
);
